program to calculate the area of a rectangle given its length
and width.

In [ ]:
l = int(input("Enter the length "))
b = int(input("Enter the breadth"))
a = l*b
print(a)

Enter the length 2
Enter the breadth2
4

program that takes two numbers from the user and calculates their
sum, difference, product, and quotient.

In [ ]:
x = int(input("Enter the 1st number "))
y = int(input("Enter the 2nd number "))
sum = x+y
print("sum = " ,sum)

diff = x-y
print("difference=",diff)

product = x*y
print("product=",product)

quo = x/y
print("quotient=",quo)

Enter the 1st number 4
Enter the 2nd number 2
sum =  6
difference= 2
product= 8
quotient= 2.0

program to convert temperature from Fahrenheit to Celsius and vice
versa, based on user input.

In [1]:
t=int(input("Enter the temperature"))
unit = int(input ("what is the unit of the above temperature ?Enter 1 for fahrenheit and 2 for celsius"))
if unit == 1:
  c = (t-32)*5/9
  print(c,"C")
else:
  f = t*9/5 + 32
  print(f,"F")

Enter the temperature0
what is the unit of the above temperature ?Enter 1 for fahrenheit and 2 for celsius2
32.0 F

In [ ]:
# To convert fahrenheit to celsius
t=int(input("Enter the temperature"))
c = (t-32)*5/9
print(c)

Enter the temperature32
0.0

In [ ]:
#To convert celsius to fahrenheit
t=int(input("Enter the temperature"))
f = (t + 32)*9/5
print(f)

Enter the temperature0
57.6

program that checks if a given number is positive, negative, or zero.

In [ ]:
x = int(input("Enter a number"))
if x>0:
  print("Number is positive")
elif x==0:
  print("Number is zero")
else:
  print("Number is negative")

Enter a number-3
Number is negative

program to determine if a year is a leap year or not

In [ ]:
x = int(input("Enter the year "))
if x%4 == 0:
  if x%100 == 0:
    print("The year is not a leap year")
  else:
    print("The year is a leap year")
elif x%400 == 0:
  print("The year is a leap year")
else:
  print("The year is not a leap year")

Enter the year1908
The year is a leap year

program that categorizes a student's grade

In [ ]:
x = int(input("Enter your grades "))
if x>89 and x<100:
  print("You have an A")
elif x>79 and x<89:
  print("You have a B")
elif x>69 and x<79:
  print("You have a C")
elif x>59 and x<69:
  print("You have a D")
elif x>0 and x<59:
  print("You have an F")
else:
  print("Invalid data")

Enter your grades90
You have an A

python loop to print nmbers from 10 to 1

In [ ]:
for number in range(10,0,-1):
  print(number)

10
9
8
7
6
5
4
3
2
1

a program that prints all the even numbers from 1 to 20 using for loop

In [ ]:
for number in range(1,21):
  if number%2 == 0:
    print(number)

2
4
6
8
10
12
14
16
18
20

program that generates and prints the multiplication table for a given number

In [ ]:
y = int(input("Enter a number "))
for number in range(0,11):
  a = y*number
  print(y,"x",number,"=",a)

Enter a number2
2 x 0 = 0
2 x 1 = 2
2 x 2 = 4
2 x 3 = 6
2 x 4 = 8
2 x 5 = 10
2 x 6 = 12
2 x 7 = 14
2 x 8 = 16
2 x 9 = 18
2 x 10 = 20